# -*- coding: utf-8 -*-
"""02_cnn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aEfqIHP5G09L45QFBn0mZwcHemyf-IpE
"""

rprint("Let's Start")

from google.colab import drive
drive.mount('/content/drive')

import tensorflow as tf

IMG_SIZE = (224,224)
BATCH_SIZE = 16

DATASET_PATH = "/content/drive/MyDrive/PCB_AI_Split_Dataset"

train_ds = tf.keras.preprocessing.image_dataset_from_directory(
    f"{DATASET_PATH}/train",
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE
)

valid_ds = tf.keras.preprocessing.image_dataset_from_directory(
    f"{DATASET_PATH}/valid",
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE
)

test_ds = tf.keras.preprocessing.image_dataset_from_directory(
    f"{DATASET_PATH}/test",
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    shuffle=False
)

print(train_ds.class_names)

import matplotlib.pyplot as plt

for images, labels in train_ds.take(1):

    print(images.shape)
    print(labels.shape)

"""CNN"""

from tensorflow.keras import layers, models

model = models.Sequential([

    # First Convolution Block
    layers.Conv2D(
        32,
        (3,3),
        activation='relu',
        input_shape=(224,224,3)
    ),

    layers.MaxPooling2D((2,2)),

    # Second Convolution Block
    layers.Conv2D(
        64,
        (3,3),
        activation='relu'
    ),

    layers.MaxPooling2D((2,2)),

    # Third Convolution Block
    layers.Conv2D(
        128,
        (3,3),
        activation='relu'
    ),

    layers.MaxPooling2D((2,2)),

    # Convert feature maps to vector
    layers.Flatten(),

    # Fully Connected Layer
    layers.Dense(
        128,
        activation='relu'
    ),

    # Output Layer
    layers.Dense(
        4,
        activation='softmax'
    )
])

model.summary()

model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

model.summary()

from tensorflow.keras import layers, models

model = models.Sequential([

    # First Convolution Block
    layers.Conv2D(
        32,
        (3,3),
        activation='relu',
        input_shape=(224,224,3)
    ),

    layers.MaxPooling2D((2,2)),

    # Second Convolution Block
    layers.Conv2D(
        64,
        (3,3),
        activation='relu'
    ),

    layers.MaxPooling2D((2,2)),

    # Third Convolution Block
    layers.Conv2D(
        128,
        (3,3),
        activation='relu'
    ),

    layers.MaxPooling2D((2,2)),

   layers.GlobalAveragePooling2D(),

layers.Dense(
    64,
    activation='relu'
),

    # Output Layer
    layers.Dense(
        4,
        activation='softmax'
    )
])

model.summary()

model.summary()

model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

history = model.fit(
    train_ds,
    validation_data=valid_ds,
    epochs=20
)

test_loss, test_acc = model.evaluate(test_ds)

print("Test Accuracy:", test_acc)
print("Test Loss:", test_loss)

import numpy as np
from sklearn.metrics import confusion_matrix, classification_report

y_true = []
y_pred = []

for images, labels in test_ds:
    predictions = model.predict(images, verbose=0)

    y_true.extend(labels.numpy())
    y_pred.extend(np.argmax(predictions, axis=1))

cm = confusion_matrix(y_true, y_pred)

print(cm)
print()
print(classification_report(
    y_true,
    y_pred,
    target_names=train_ds.class_names
))

import matplotlib.pyplot as plt

acc = history.history['accuracy']
val_acc = history.history['val_accuracy']

loss = history.history['loss']
val_loss = history.history['val_loss']

epochs = range(1, len(acc) + 1)

plt.figure(figsize=(12,5))

plt.subplot(1,2,1)
plt.plot(epochs, acc, label='Train Accuracy')
plt.plot(epochs, val_acc, label='Validation Accuracy')
plt.title('Accuracy vs Epochs')
plt.legend()

plt.subplot(1,2,2)
plt.plot(epochs, loss, label='Train Loss')
plt.plot(epochs, val_loss, label='Validation Loss')
plt.title('Loss vs Epochs')
plt.legend()

plt.show()

import numpy as np
import matplotlib.pyplot as plt

class_names = train_ds.class_names

wrong_images = []
wrong_actual = []
wrong_pred = []
wrong_conf = []

for images, labels in test_ds:

    preds = model.predict(images, verbose=0)

    pred_classes = np.argmax(preds, axis=1)

    for i in range(len(labels)):

        actual = labels[i].numpy()
        predicted = pred_classes[i]

        if actual != predicted:

            wrong_images.append(images[i].numpy().astype("uint8"))

            wrong_actual.append(class_names[actual])

            wrong_pred.append(class_names[predicted])

            wrong_conf.append(np.max(preds[i]))

print("Total Wrong Predictions:", len(wrong_images))

plt.figure(figsize=(15,5))

for i in range(len(wrong_images)):

    plt.subplot(1, len(wrong_images), i+1)

    plt.imshow(wrong_images[i])

    plt.title(
        f"Actual: {wrong_actual[i]}\n"
        f"Pred: {wrong_pred[i]}\n"
        f"Conf: {wrong_conf[i]:.2f}"
    )

    plt.axis("off")

plt.tight_layout()
plt.show()

from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras import layers, models

base_model = MobileNetV2(
    input_shape=(224,224,3),
    include_top=False,
    weights='imagenet'
)

base_model.trainable = False

model_mobilenet = models.Sequential([

    base_model,

    layers.GlobalAveragePooling2D(),

    layers.Dense(
        64,
        activation='relu'
    ),

    layers.Dropout(0.3),

    layers.Dense(
        4,
        activation='softmax'
    )

])

model_mobilenet.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

model_mobilenet.summary()

history_mobilenet = model_mobilenet.fit(
    train_ds,
    validation_data=valid_ds,
    epochs=15
)

test_loss, test_acc = model_mobilenet.evaluate(test_ds)

print("Test Accuracy:", test_acc)
print("Test Loss:", test_loss)

import numpy as np
from sklearn.metrics import confusion_matrix, classification_report

y_true = []
y_pred = []

for images, labels in test_ds:

    predictions = model_mobilenet.predict(images, verbose=0)

    y_true.extend(labels.numpy())
    y_pred.extend(np.argmax(predictions, axis=1))

cm = confusion_matrix(y_true, y_pred)

print(cm)
print()

print(
    classification_report(
        y_true,
        y_pred,
        target_names=train_ds.class_names
    )
)

import matplotlib.pyplot as plt

wrong_images = []
wrong_actual = []
wrong_pred = []
wrong_conf = []

for images, labels in test_ds:

    predictions = model_mobilenet.predict(images, verbose=0)

    pred_classes = np.argmax(predictions, axis=1)

    for i in range(len(labels)):

        actual = labels[i].numpy()
        predicted = pred_classes[i]

        if actual != predicted:

            wrong_images.append(images[i].numpy().astype("uint8"))

            wrong_actual.append(train_ds.class_names[actual])

            wrong_pred.append(train_ds.class_names[predicted])

            wrong_conf.append(np.max(predictions[i]))

print("Wrong predictions:", len(wrong_images))

plt.figure(figsize=(15,5))

for i in range(len(wrong_images)):

    plt.subplot(1, len(wrong_images), i+1)

    plt.imshow(wrong_images[i])

    plt.title(
        f"Actual: {wrong_actual[i]}\n"
        f"Pred: {wrong_pred[i]}\n"
        f"Conf: {wrong_conf[i]:.2f}"
    )

    plt.axis("off")

plt.tight_layout()
plt.show()